language: node_js
sudo: required
node_js: "stable"
install:
  - npm install
script:
  - npm start
after_script:
  - echo $(git  diff-tree --no-commit-id --name-only -r $(git log --pretty=format:'%h' -n 1))
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master